stages:
  download_data:
    cmd: Rscript R/download.R
    deps:
    - R/download.R
    outs:
    - cache/download/
  make_Column_Names:
    cmd: Rscript R/Column_Names.R
    deps:
    - R/Column_Names.R
    - cache/download
    outs:
    - cache/README
  make_parquet:
    cmd: Rscript R/build.R
    deps:
    - R/build.R
    - cache/
    outs:
    - data/
