stages:
  download_data:
    cmd: stages/01_download.sh
    deps:
    - stages/01_download.sh
    outs:
    - download
  build:
    cmd: stages/02_unzip.sh
    deps:
    - stages/02_unzip.sh
    - download
    outs:
    - brick
