stages:
  download_data:
    cmd: stages/01_download.sh
    deps:
    - stages/01_download.sh
    outs:
    - download
  process:
    cmd: stages/02_process.sh
    deps:
    - stages/02_process.sh
    - download
    outs:
    - raw
  build:
    cmd: stages/03_build.sh
    deps:
    - stages/03_build.sh
    - download
    outs:
    - brick
